name: Build and Push Docker image to GHCR

on:
  workflow_dispatch:
  #push:
    #branches:
      #- main  # 根据你的分支情况调整
  #pull_request:
    #branches:
      #- main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/whmcs_watchdog:latest  # 替换为你的镜像名称

    - name: Cleanup
      uses: docker/build-push-action@v2
      with:
        cleanup: true
